month: March 2025
phases:
  Build:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Code:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Deploy:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Monitor:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Operate:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Plan:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Release:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
  Test:
    total_issues: 0
    week1:
      completed: false
      issues_count: 0
    week2:
      completed: false
      issues_count: 0
    week3:
      completed: false
      issues_count: 0
    week4:
      completed: false
      issues_count: 0
