name: DevOps Checklist Automation

permissions:
  contents: write  # Permite escribir en el repositorio (para commit y push)
  issues: read     # Permite leer issues (necesario para acceder a los datos de GitHub)

on:
  schedule:
    - cron: "0 0 1 * *"  # Ejecuta el workflow el primer día de cada mes a las 00:00 UTC
  push:
    branches:
      - main  # Ejecuta el workflow cuando hay un push a la rama main
  pull_request:
    branches:
      - main  # Ejecuta el workflow cuando hay un pull request a la rama main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  devops_checklist:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Usa la versión más reciente de Python 3

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests prettytable

      # Step 4: Run DevOps Checklist script
      - name: Run DevOps Checklist script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub para autenticación
          REPO_OWNER: ${{ github.repository_owner }}  # Obtiene el propietario del repositorio
          REPO_NAME: ${{ github.repository }}        # Obtiene el nombre del repositorio
        run: |
          python .github/scripts/devops_checklist.py  # Ejecuta el script de Python

      # Step 5: Check if JSON file is generated
      - name: Check if JSON file is generated
        run: |
          if [ -f "devops_check_sheet.json" ]; then
            echo "JSON file generated"
          else
            echo "JSON file not found"
            exit 1
          fi

      # Step 6: Upload JSON file as artifact
      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: devops-checklist
          path: devops_checklists.json

      # Step 7: Check for changes before committing
      - name: Check for changes before committing
        run: |
          git diff --exit-code || echo "Changes detected"

      # Step 8: Commit and push JSON file
      - name: Commit and push JSON file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add devops_checklists.json
          git commit -m 'Update DevOps Checklist for $(date +"%Y-%m-%d")' || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || echo "No changes to push"