name: DevOps Checklist Automation

on:
  schedule:
    # Ejecuta el workflow el primer día de cada mes a las 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  generate-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Especifica la versión de Python que deseas usar

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests prettytable

    - name: Run DevOps Checklist Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub para autenticación
        REPO_OWNER: ${{ github.repository_owner }}  # Obtiene el propietario del repositorio
        REPO_NAME: ${{ github.repository }}  # Obtiene el nombre del repositorio
      run: |
        python -c "
        from your_script_module import DevOpsChecklist
        checklist = DevOpsChecklist('$GITHUB_TOKEN', '$REPO_OWNER', '$REPO_NAME')
        checklist.generate_current_month()
        checklist.display_month_checklist(checklist.monthly_data['year'], checklist.monthly_data['month'])
        checklist.save_to_json()
        "

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add devops_checklists.json
        git commit -m "Update DevOps Checklist for $(date +'%Y-%m-%d')"
        git push