name: Generar Hoja de Verificación

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Esto permite activarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas numpy

    - name: Generar hoja de verificación
      run: python checksheet.py

    - name: Subir artefacto
      uses: actions/upload-artifact@v2
      with:
        name: hoja-verificacion
        path: artifacts/
        retention-days: 90