name: Monthly DevOps Checklist

on:
  schedule:
    # Ejecutar el primer día de cada mes a las 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:
    # Permitir ejecución manual

jobs:
  generate-checklist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      
      - name: Generate monthly checklist
        run: python checklist.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit and push checklist files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Obtener año y mes actuales
          YEAR=$(date +"%Y")
          MONTH=$(date +"%m")
          
          # Agregar archivos generados
          git add devops_checklist_${YEAR}_${MONTH}.yml
          git add devops_checklist_${YEAR}_${MONTH}.md
          
          # Commit y push solo si hay cambios
          git diff --staged --quiet || (git commit -m "Generar DevOps Checklist para ${YEAR}-${MONTH}" && git push)
