name: Generate Better Health Checklist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate health checklist
      run: |
        cd $GITHUB_WORKSPACE
        python .github/scripts/generate_checklist.py

    - name: Upload checklist artifact
      uses: actions/upload-artifact@v3
      with:
        name: health-checklist
        path: ./health_checklist.md
        if-no-files-found: error