name: Histogram Issues Report Generator

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub
  schedule:
    - cron: '0 0 1 * *'  # Ejecuta el primer día de cada mes a las 00:00 UTC

jobs:
  generate-histogram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib
      
      - name: Run histogram generator script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python .github/scripts/histogram_general_report.py
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
           mv checksheet_table.png ishikawa/
          mv checksheet_data.json ishikawa/
          git add ishikawa/histogram_issues.png 
          git commit -m "Update issues histogram report for $(date +'%B %Y')" || echo "No changes to commit"
          git push
